### PR TITLE
(MCO-773) Add mcollective.gemspec so we can generate a gem

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@McdonaldSeanp does this make sense? We already generate a gem, how does that work?

**Comment by McdonaldSeanp** [comment]
Yeah, we dont generate an MCO gem as of now

**Comment by ripienaar** [comment]
There has never been a mcollective gem only a client gem. This is on purpose because you can't use such a thing - mcollective is a daemon with confit requirements, needs a service script and more. You can't deliver a working mcollective as a gem

**Comment by mruzicka** [comment]
@tampakrap why do you need the gem, and how do you address the issues mentioned by @ripienaar?

**Comment by tampakrap** [comment]
take a look at the discussion at the ticket please. I'll be glad to provide further info as well https://tickets.puppetlabs.com/browse/MCO-773

**Pull request closed without merging**
