### PR TITLE
Mergeup for 2.8.9 release

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Also includes changes destined for 2.9.0 release, but not the tag.

**Comment by MikaelSmith** [comment]
Did you mean to do this against master? Is the plan to merge to master, then merge master to stable for 2.9.0?

**Comment by underscorgan** [comment]
nope, reopening against stable

**Comment by underscorgan** [comment]
reopened https://github.com/puppetlabs/marionette-collective/pull/389

**Pull request closed without merging**
