### PR TITLE
(maint) Add comment about updating limits with systemd

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Seems useful. I suspect there are other places this should apply, but I don't see any off the top.

**Comment by MikaelSmith** [comment]
I think I'd like a ticket for this, to track the conceptual idea (documenting updating limits with systemd) in case we later realize it's needed elsewhere.

**Comment by underscorgan** [comment]
@MikaelSmith there's an internal RE ticket for this, and I've updated it in puppet, mco, pxp-agent, and ezbake. I didn't want to reference an internal ticket, and didn't know if it was useful to open tickets for everything ¯\_(ツ)_/¯

**Comment by MikaelSmith** [comment]
Ok

**Comment by underscorgan** [comment]
woo thanks!

**Pull request merged**
