### PR TITLE
DO NOT MERGE - MCO-517 AIO paths

### PR DESCRIPTION
**Pull request by richardc**
This PR is here so we can have travis coverage, and can easily find the code/collaborate.

Don't merge (yet)

### CODE REVIEW

**Comment by haus** [comment]
@richardc with the cfacter and facter work, @whopper made it so that we would try the new location first, and fall back to the old location. that seems like it would be a good idea here as well.

**Comment by richardc** [comment]
@haus New and old location of what?

**Comment by haus** [comment]
@richardc sorry, wasn't specific. Things like configfile, where we could check file existence of the new and fall back to the old. Specifically, I was thinking of `bin/mcollectived` and `lib/mcollective/util.rb` as the places where that makes sense in the current PR.

**Comment by richardc** [comment]
I'd sooner we just fail to load a config file if it isn't in the new location, rather than play a round of 'guess which config file will be respected'

**Comment by richardc** [comment]
A new branch for this has been created as we have multiple contributors/contributions to manage - https://github.com/puppetlabs/marionette-collective/tree/aio-agent

**Pull request closed without merging**
