### PR TITLE
(MCO-688) Fix mco plugins installation when using puppet-agent on Deb…

### PR DESCRIPTION
**Pull request by mcanevet**
…ian family systems

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@stahnma can you have someone take a look? Does this look right?

**Comment by raphink** [comment]
:+1:

**Comment by mcanevet** [comment]
@stahnma @MikaelSmith any news on this?
I'd really like to see this old bug fixed so that we can use mcollective plugins again on Debian

**Comment by underscorgan** [comment]
I don't have any background on mco plugin packaging, but is this something that should be fixed at this level or is puppet-agent a dependency that should be added to the individual plugins? With pathing changes I also wonder if the plugins will still work with puppet-agent. 

If changes need to be made at this level we should keep the deb and rpm packaging in sync so we can be as consistent as possible.

**Comment by mcanevet** [comment]
@underscorgan this patch will actually add `puppet-agent` as dependency to individual plugins (once repackaged). This fix is need because mco plugins currently conflicts with puppet-agent on Debian-like OSes (since the release of Puppet AIO packaging...).
This critical bug for Debian users has been reported at least 10 months ago (MCO-688, MCO-722) and this simple patch fixes it.

**Comment by mcanevet** [comment]
@underscorgan @stahnma @MikaelSmith what prevent this to be merged?
Can I help on something?

**Comment by underscorgan** [comment]
@MikaelSmith have you had a chance to dig into this more yet?

**Comment by MikaelSmith** [comment]
This doesn't fix the issue with having remote repositories with the correct dependencies, but fixing mco's packaging is valuable.

With this patch on Ubuntu 14.04, I can now
- install `puppet-agent`
- install a bunch of dependencies (`build-essential devscripts debhelper cdbs dpatch`)
- clone a plugin (such as mcollective-service-agent)
- package it (mco plugin package)
- and install it

Without this patch, I get errors about missing a dependency: `mcollective-common`.

**Comment by MikaelSmith** [comment]
Working on figuring out what other steps should happen based on this. I don't have a problem with merging this PR, except it's not really sufficient to close MCO-722. I don't agree with Richard's conclusion that MCO-688 and MCO-722 are duplicates.

@mcanevet would you mind retagging this for MCO-688?

**Comment by underscorgan** [comment]
Is it possible to add a similar patch for el packaging so we don't end up
with packaging differences between el and deb?

On Thu, Jun 23, 2016, 16:39 Michael Smith <notifications@github.com> wrote:

> Working on figuring out what other steps should happen based on this. I
> don't have a problem with merging this PR, except it's not really
> sufficient to close MCO-722. I don't agree with Richard's conclusion that
> MCO-688 and MCO-722 are duplicates.
>
> @mcanevet <https://github.com/mcanevet> would you mind retagging this for
> MCO-688?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/puppetlabs/marionette-collective/pull/381#issuecomment-228217401>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAhx-MIHCh9-KDuAbKOOf7KdxDzQgAJnks5qOxlDgaJpZM4IlLno>
> .
>
-- 
Morgan Rhodes
morgan@puppet.com
Release Engineer

**Comment by MikaelSmith** [comment]
The place to fix this might be in https://github.com/puppetlabs/marionette-collective/blob/master/lib/mcollective/pluginpackager/agent_definition.rb#L16-L22. Or, it might take a bit more work to clean it up. I may be able to help with that.

**Comment by mcanevet** [comment]
@MikaelSmith I changed the commit message to tag it for MCO-688

**Comment by mcanevet** [comment]
@underscorgan AFAIK el is not impacted with this bug. At least I can install mcollective plugins found here : http://yum.puppetlabs.com/el/7/products/x86_64/ with AIO package.

**Comment by MikaelSmith** [comment]
Ok, I think this is ok. I'm going to try to spend some time on MCO-722 during #puppethack next week, and do any more cleanup that's needed.

**Comment by MikaelSmith** [comment]
Thanks @mcanevet!

**Comment by underscorgan** [comment]
@mcanevet ahh, ok, cool! thanks!

**Comment by raphink** [comment]
Great, thanks for merging!

**Pull request merged**
