### PR TITLE
Updates to make interbroker links more stable.

### PR DESCRIPTION
**Pull request by dforste**
Updates to messageEvictionStrategy to prevent buildup of messages in queue for topics on larger clusters.

### CODE REVIEW

**Comment by dforste** [comment]
This relates to https://tickets.puppetlabs.com/browse/MCO-58

**Comment by dforste** [comment]
This seems to fall under the Trivial Patch Exemption Policy as it "introduce no new functionality."

**Comment by MikaelSmith** [comment]
It should be fine; submitting commits via the web interface doesn't work well with our bot either.

**Comment by dforste** [comment]
Ya not a problem the biggest part is the addition of a pruning strategy otherwise topics keep an ungodly amount of messages around. This seems to be the cause of some instability. Another recommendation is to upgrade to a full mesh as that helps with intermittent network or link issues. 

````
<messageEvictionStrategy>
  <oldestMessageEvictionStrategy/>
</messageEvictionStrategy>
<pendingMessageLimitStrategy>
  <prefetchRatePendingMessageLimitStrategy
    multiplier="2"
  />
</pendingMessageLimitStrategy>
````

**Pull request merged**
