### PR TITLE
(maint) Add runonce test, use default plugin config

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by johnduarte** [comment]
@MikaelSmith should this be targeted at master?

**Comment by MikaelSmith** [comment]
I think stable will work. It doesn't rely on any changes in master, and improves test coverage.

**Comment by johnduarte** [comment]
Tested using Ubuntu-1604 and Windows 2012r2, this change results in a passing test suite.

Ubuntu 16.04
```
$ cat log/redhat7-64m-ubuntu1604-64mco_master.a-21d38ab0-3652-4138-a018-97523cfafc92.yaml/2017-02-28_16_10_16/tests-summary.txt
      Test Suite: tests @ 2017-02-28 16:15:46 -0800

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 105.95 seconds
      Average Test Time: 21.19 seconds
              Attempted: 5
                 Passed: 4
                 Failed: 0
                Errored: 0
                Skipped: 1
                Pending: 0
                  Total: 5

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:
```

Windows 2012r2
```
$ cat log/redhat7-64m-windows2012r2-64mco_master.a-4e21f15c-fa06-4906-aff1-e13501610a64.yaml/2017-02-28_16_19_44/tests-summary.txt
      Test Suite: tests @ 2017-02-28 16:26:47 -0800

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 223.71 seconds
      Average Test Time: 44.74 seconds
              Attempted: 5
                 Passed: 5
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 5

      - Specific Test Case Status -

Failed Tests Cases:
Errored Tests Cases:
Skipped Tests Cases:
Pending Tests Cases:
```

**Pull request merged**
